### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by hannojg** [satya164/react-native-tab-view#1015]
Can't get this working with typescript, it says:

```text
node_modules/react-native-tab-view/lib/typescript/src/SceneMap.d.ts:4:8 - error TS2339: Property 'route' does not exist on type '{}'.

4 }): ({ route, jumpTo, position }: T) => JSX.Element;
         ~~~~~

node_modules/react-native-tab-view/lib/typescript/src/SceneMap.d.ts:4:15 - error TS2339: Property 'jumpTo' does not exist on type '{}'.

4 }): ({ route, jumpTo, position }: T) => JSX.Element;
                ~~~~~~

node_modules/react-native-tab-view/lib/typescript/src/SceneMap.d.ts:4:23 - error TS2339: Property 'position' does not exist on type '{}'.

4 }): ({ route, jumpTo, position }: T) => JSX.Element;
                        ~~~~~~~~

```

**Comment by punksta** [comment]
Got it too. The problem is here: https://github.com/react-native-community/react-native-tab-view/blob/master/src/SceneMap.tsx#L12 `{ route, jumpTo, position }` should be present in parent of `T`

**Comment by punksta** [comment]
repro:
```
git clone git@github.com:react-native-community/react-native-tab-view.git
npm ci
npm run typescript
```
> `Found 7 errors.`

**Comment by satya164** [comment]
@punksta that's not how you setup this repo. anyway the op's issue seems to be with updated typescript.

**Comment by Vannevelj** [comment]
I can confirm I've got the same issue (react-native-tab-view@2.13.0, typescript@3.9.7).

After bumping react-native-tab-view to 2.15.0, the errors were solved.
